token = "" # Токен сообщества ВКонтакте

[text]
buttons_text = "https://vk.com/shuex"
message_text = "🤘🏻" # Если короче 4096 байтов - будет повторён максимальное кол-во раз

[misc]
logging_level = "DEBUG"
delay = 0.33